name: deploy to cloudflare worker
on:
  push:
    branches:
      - master
jobs:
  deploy_worker:
    name: build and deploy cloudflare worker
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: update submodules
        run: |
          git submodule init
          git submodule update --recursive
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
      - name: zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./bundle.zip ./
      - name: default deploy
        uses: cloudflare/wrangler-action@12.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
